/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduledRouteImport } from './routes/_authenticated/scheduled'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPostedRouteImport } from './routes/_authenticated/posted'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedMediaPrepRouteImport } from './routes/_authenticated/media-prep'
import { Route as ApiPublicLicenseStatusRouteImport } from './routes/api/public/license-status'
import { Route as ApiPublicActivateRouteImport } from './routes/api/public/activate'
import { Route as AuthenticatedPostIdRouteImport } from './routes/_authenticated/post.$id'
import { Route as ApiPublicHooksStripeRouteImport } from './routes/api/public/hooks/stripe'
import { Route as ApiPublicHooksRunPipelineRouteImport } from './routes/api/public/hooks/run-pipeline'
import { Route as ApiPublicHooksRunDueRouteImport } from './routes/api/public/hooks/run-due'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduledRoute = AuthenticatedScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostedRoute = AuthenticatedPostedRouteImport.update({
  id: '/posted',
  path: '/posted',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaPrepRoute = AuthenticatedMediaPrepRouteImport.update({
  id: '/media-prep',
  path: '/media-prep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicLicenseStatusRoute = ApiPublicLicenseStatusRouteImport.update({
  id: '/api/public/license-status',
  path: '/api/public/license-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicActivateRoute = ApiPublicActivateRouteImport.update({
  id: '/api/public/activate',
  path: '/api/public/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostIdRoute = AuthenticatedPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksStripeRoute = ApiPublicHooksStripeRouteImport.update({
  id: '/api/public/hooks/stripe',
  path: '/api/public/hooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunPipelineRoute =
  ApiPublicHooksRunPipelineRouteImport.update({
    id: '/api/public/hooks/run-pipeline',
    path: '/api/public/hooks/run-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunDueRoute = ApiPublicHooksRunDueRouteImport.update({
  id: '/api/public/hooks/run-due',
  path: '/api/public/hooks/run-due',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/media-prep': typeof AuthenticatedMediaPrepRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/posted': typeof AuthenticatedPostedRoute
  '/products': typeof AuthenticatedProductsRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/license-status': typeof ApiPublicLicenseStatusRoute
  '/api/public/hooks/run-due': typeof ApiPublicHooksRunDueRoute
  '/api/public/hooks/run-pipeline': typeof ApiPublicHooksRunPipelineRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
}
export interface FileRoutesByTo {
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/media-prep': typeof AuthenticatedMediaPrepRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/posted': typeof AuthenticatedPostedRoute
  '/products': typeof AuthenticatedProductsRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/': typeof AuthenticatedIndexRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/license-status': typeof ApiPublicLicenseStatusRoute
  '/api/public/hooks/run-due': typeof ApiPublicHooksRunDueRoute
  '/api/public/hooks/run-pipeline': typeof ApiPublicHooksRunPipelineRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/_authenticated/media-prep': typeof AuthenticatedMediaPrepRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/posted': typeof AuthenticatedPostedRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/scheduled': typeof AuthenticatedScheduledRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/post/$id': typeof AuthenticatedPostIdRoute
  '/api/public/activate': typeof ApiPublicActivateRoute
  '/api/public/license-status': typeof ApiPublicLicenseStatusRoute
  '/api/public/hooks/run-due': typeof ApiPublicHooksRunDueRoute
  '/api/public/hooks/run-pipeline': typeof ApiPublicHooksRunPipelineRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/auth'
    | '/media-prep'
    | '/pipeline'
    | '/posted'
    | '/products'
    | '/queue'
    | '/scheduled'
    | '/settings'
    | '/upload'
    | '/post/$id'
    | '/api/public/activate'
    | '/api/public/license-status'
    | '/api/public/hooks/run-due'
    | '/api/public/hooks/run-pipeline'
    | '/api/public/hooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activate'
    | '/auth'
    | '/media-prep'
    | '/pipeline'
    | '/posted'
    | '/products'
    | '/queue'
    | '/scheduled'
    | '/settings'
    | '/upload'
    | '/'
    | '/post/$id'
    | '/api/public/activate'
    | '/api/public/license-status'
    | '/api/public/hooks/run-due'
    | '/api/public/hooks/run-pipeline'
    | '/api/public/hooks/stripe'
  id:
    | '__root__'
    | '/_authenticated'
    | '/activate'
    | '/auth'
    | '/_authenticated/media-prep'
    | '/_authenticated/pipeline'
    | '/_authenticated/posted'
    | '/_authenticated/products'
    | '/_authenticated/queue'
    | '/_authenticated/scheduled'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/_authenticated/'
    | '/_authenticated/post/$id'
    | '/api/public/activate'
    | '/api/public/license-status'
    | '/api/public/hooks/run-due'
    | '/api/public/hooks/run-pipeline'
    | '/api/public/hooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  AuthRoute: typeof AuthRoute
  ApiPublicActivateRoute: typeof ApiPublicActivateRoute
  ApiPublicLicenseStatusRoute: typeof ApiPublicLicenseStatusRoute
  ApiPublicHooksRunDueRoute: typeof ApiPublicHooksRunDueRoute
  ApiPublicHooksRunPipelineRoute: typeof ApiPublicHooksRunPipelineRoute
  ApiPublicHooksStripeRoute: typeof ApiPublicHooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduled': {
      id: '/_authenticated/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof AuthenticatedScheduledRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posted': {
      id: '/_authenticated/posted'
      path: '/posted'
      fullPath: '/posted'
      preLoaderRoute: typeof AuthenticatedPostedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media-prep': {
      id: '/_authenticated/media-prep'
      path: '/media-prep'
      fullPath: '/media-prep'
      preLoaderRoute: typeof AuthenticatedMediaPrepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/license-status': {
      id: '/api/public/license-status'
      path: '/api/public/license-status'
      fullPath: '/api/public/license-status'
      preLoaderRoute: typeof ApiPublicLicenseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activate': {
      id: '/api/public/activate'
      path: '/api/public/activate'
      fullPath: '/api/public/activate'
      preLoaderRoute: typeof ApiPublicActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post/$id': {
      id: '/_authenticated/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AuthenticatedPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/stripe': {
      id: '/api/public/hooks/stripe'
      path: '/api/public/hooks/stripe'
      fullPath: '/api/public/hooks/stripe'
      preLoaderRoute: typeof ApiPublicHooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-pipeline': {
      id: '/api/public/hooks/run-pipeline'
      path: '/api/public/hooks/run-pipeline'
      fullPath: '/api/public/hooks/run-pipeline'
      preLoaderRoute: typeof ApiPublicHooksRunPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-due': {
      id: '/api/public/hooks/run-due'
      path: '/api/public/hooks/run-due'
      fullPath: '/api/public/hooks/run-due'
      preLoaderRoute: typeof ApiPublicHooksRunDueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMediaPrepRoute: typeof AuthenticatedMediaPrepRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPostedRoute: typeof AuthenticatedPostedRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedScheduledRoute: typeof AuthenticatedScheduledRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPostIdRoute: typeof AuthenticatedPostIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMediaPrepRoute: AuthenticatedMediaPrepRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPostedRoute: AuthenticatedPostedRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedScheduledRoute: AuthenticatedScheduledRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPostIdRoute: AuthenticatedPostIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivateRoute: ActivateRoute,
  AuthRoute: AuthRoute,
  ApiPublicActivateRoute: ApiPublicActivateRoute,
  ApiPublicLicenseStatusRoute: ApiPublicLicenseStatusRoute,
  ApiPublicHooksRunDueRoute: ApiPublicHooksRunDueRoute,
  ApiPublicHooksRunPipelineRoute: ApiPublicHooksRunPipelineRoute,
  ApiPublicHooksStripeRoute: ApiPublicHooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
