// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function createAuthMiddleware(allowCron: boolean) {
  return createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const request = getRequest();
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Response(message, { status: 500 });
    }
    
    if (!request?.headers) {
      throw new Response('Unauthorized: No request headers available', { status: 401 });
    }

    const cronSecret = process.env.CRON_SECRET;
    const isCron = Boolean(allowCron && cronSecret && request.headers.get('x-cron-secret') === cronSecret);
    const authHeader = request.headers.get('authorization');
    if (!authHeader && !isCron) {
      throw new Response('Unauthorized: No authorization header provided', { status: 401 });
    }

    if (authHeader && !authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
    }

    const token = authHeader?.replace('Bearer ', '');
    if (authHeader && !token) {
      throw new Response('Unauthorized: No token provided', { status: 401 });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: token ? { headers: { Authorization: `Bearer ${token}` } } : {},
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    let claims: { sub: string; [key: string]: unknown };
    if (token) {
      const { data, error } = await supabase.auth.getClaims(token);
      if (error || !data?.claims) {
        throw new Response('Unauthorized: Invalid token', { status: 401 });
      }
      if (!data.claims.sub) {
        throw new Response('Unauthorized: No user ID found in token', { status: 401 });
      }
      claims = data.claims as typeof claims;
      const { data: active, error: membershipError } = await supabase.rpc('is_member_active', {
        _user_id: claims.sub,
      });
      if (membershipError) {
        console.error('[Billing] Could not verify membership', membershipError);
        throw new Response('Unable to verify app access. Try again shortly.', { status: 503 });
      }
      if (!active) {
        throw new Response('An active $300 access payment is required.', { status: 402 });
      }
    } else {
      claims = { sub: 'cron' };
    }

    return next({
      context: {
        supabase,
        userId: claims.sub,
        claims,
      },
    })
  }
  )
}

export const requireSupabaseAuth = createAuthMiddleware(false)
export const requireSupabaseAuthOrCron = createAuthMiddleware(true)
